### ISSUE TITLE
Add shawdow jar plugin to build.gradle to create a fat jar

### ISSUE THREAD

**Issue by relentless-pursuit** [checkstyle/test-configs#161]
```
Downloading https://services.gradle.org/distributions/gradle-8.6-bin.zip
............10%.............20%............30%.............40%.............50%............[60](https://github.com/checkstyle-gsoc/checkstyle/actions/runs/10378866510/job/28735951176#step:6:61)%.............70%.............80%............90%.............100%
Welcome to Gradle 8.6!
Here are the highlights of this release:
 - Configurable encryption key for configuration cache
 - Build init improvements
 - Build authoring improvements
For more details see https://docs.gradle.org/8.6/release-notes.html
Starting a Gradle Daemon (subsequent builds will be faster)
Note: /home/runner/work/checkstyle/checkstyle/test-configs/extractor/src/main/java/com/example/extractor/ConfigSerializer.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
> Task :compileJava
> Task :processResources
> Task :classes
> Task :jar
> Task :startScripts
> Task :distTar
> Task :distZip
> Task :assemble
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
For more on this, please refer to https://docs.gradle.org/8.6/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
BUILD SUCCESSFUL in 22s
6 actionable tasks: 6 executed
Path to CheckstyleExampleExtractor in JAR: com/example/extractor/CheckstyleExampleExtractor.class
Copying src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/methodparampad/InputMethodParamPadRecords.java to src/test/resources/src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/methodparampad
Processing file: src/test/resources/src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/methodparampad/InputMethodParamPadRecords.java
Exception in thread "main" java.lang.NoClassDefFoundError: com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser
	at com.example.extractor.CheckstyleExampleExtractor.getTemplateFilePathForInputFile(CheckstyleExampleExtractor.java:1[81](https://github.com/checkstyle-gsoc/checkstyle/actions/runs/10378866510/job/28735951176#step:6:82))
	at com.example.extractor.CheckstyleExampleExtractor.processInputFile(CheckstyleExampleExtractor.java:159)
	at com.example.extractor.CheckstyleExampleExtractor.main(CheckstyleExampleExtractor.java:123)
Caused by: java.lang.ClassNotFoundException: com.puppycrawl.tools.checkstyle.bdd.InlineConfigParser
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
	... 3 more
```

```
      - name: Generate configs
        run: |
          # Navigate to the extractor directory
          cd test-configs/extractor
      
          # Build the project without running tests
          ./gradlew assemble -x test
      
          # Extract and display the path of the CheckstyleExampleExtractor class inside the JAR file
          CLASS_PATH=$(jar tf build/libs/extractor.jar | grep "CheckstyleExampleExtractor.class")
          
          # Echo the full class path
          echo "Path to CheckstyleExampleExtractor in JAR: $CLASS_PATH"
      
          # Define the classpath to include the JAR file
          JAR_PATH="build/libs/extractor.jar"
          
          # Define the fully qualified class name (without .java extension)
          MAIN_CLASS="com.example.extractor.CheckstyleExampleExtractor"
      
          # Copy the changed files into the extractor directory, maintaining their original directory structure
          for FILE in ${{ steps.find_inputs.outputs.files }}; do
            TARGET_DIR="src/test/resources/$(dirname "$FILE")"
            echo "Copying $FILE to $TARGET_DIR"
            mkdir -p "$TARGET_DIR"
            cp "../../$FILE" "$TARGET_DIR"
          done
      
          # Run the Java program with the necessary arguments
          for FILE in ${{ steps.find_inputs.outputs.files }}; do
            TARGET_FILE="src/test/resources/$FILE"
            echo "Processing file: $TARGET_FILE"
            if [ ! -f "$TARGET_FILE" ]; then
              echo "Error: Input file does not exist: $TARGET_FILE"
              continue
            fi
      
            BASE_PATH="../.ci-temp/checkstyle"  # Base path or other relevant argument
            
            # Define output file path
            OUTPUT_FILE="/tmp/output-config.xml"
            
            # Run the Java program with the necessary arguments
            java -cp "$JAR_PATH" "$MAIN_CLASS" "$BASE_PATH" --input-file "$TARGET_FILE" "$OUTPUT_FILE"
            
            # Check if the output file was created
            if [ ! -f "$OUTPUT_FILE" ]; then
              echo "Error: Output file was not created"
              continue
            fi
      
            echo "Successfully processed file: $TARGET_FILE"
            echo "Output file: $OUTPUT_FILE"
          done  # Close the for loop
```

So, I have to run the extractor as a gradle and from the jar, i need to call the class having main method. But, it complains of not finding dependencies like `InlineConfigParser.java`. I feel i need to create a fat jar. And, it needs a shawdow jar plugin in the `build.gradle`.

**Comment by relentless-pursuit** [comment]
Before ading the plguin:
<img width="749" alt="image" src="https://github.com/user-attachments/assets/cdb23f39-a2ca-4a53-b224-14875f3edec5">

```
piyushkumarsadangi@piyushs-MacBook-Air extractor % jar tf build/libs/your-project-name-version.jar | grep "com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.class"
java.nio.file.NoSuchFileException: build/libs/your-project-name-version.jar
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
        at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:171)
        at java.base/java.nio.file.Files.readAttributes(Files.java:1853)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1445)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:724)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:251)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:180)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:151)
        at jdk.jartool/sun.tools.jar.Main.list(Main.java:1527)
        at jdk.jartool/sun.tools.jar.Main.run(Main.java:367)
        at jdk.jartool/sun.tools.jar.Main.main(Main.java:1708)
piyushkumarsadangi@piyushs-MacBook-Air extractor % 

```

After plguin:
<img width="733" alt="image" src="https://github.com/user-attachments/assets/a2806de9-74af-42a4-8fa6-0b267ed71bd0">


```
piyushkumarsadangi@piyushs-MacBook-Air extractor % jar tf build/libs/extractor-all.jar | grep "com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.class"            
com/puppycrawl/tools/checkstyle/bdd/InlineConfigParser.class

```
